# 강의노트

### 데이터사이언스개론 Numpy

In [1]:
import numpy as np

###### 리스트는 데이터를 다루는데 사용하지만 array는 계산을 하기위해 만든 것이다.

In [3]:
my_list = [1, 2, 10]
print(my_list * 3)

[1, 2, 10, 1, 2, 10, 1, 2, 10]


In [5]:
my_array = np.array(my_list)
print(my_array * 3)

[ 3  6 30]


#### 2차원 리스트로부터 2차원 배열을 만드는 예

In [6]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(data)
type(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [12]:
arr = np.array(data) # 리스트를 array로

print(arr)
type(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

#### array 값은 모두 같은 타입일 때만 변경이 가능하다.

In [10]:
data1 = ["1","2","3"]

data2 = np.array(data1)
print(data2)
type(data2)

['1' '2' '3']


numpy.ndarray

In [16]:
arr.dtype

dtype('int32')

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr[1,2], arr[1][2], arr[0][2]

(6, 6, 3)

In [22]:
z = np.zeros((4, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
O = np.ones((3, 3))
O

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
y = np.arange(1, 10, 2)
print(type(y))
y

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

In [29]:
y.dtype

dtype('int32')

In [30]:
x = range(5)
print(type(x))
x

<class 'range'>


range(0, 5)

In [32]:
# 레인지(범위) 형태로 배열을 만드는 법

y = np.arange(5)
print(type(y))
y

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [34]:
x[2],y[2]

(2, 2)

In [36]:
# 데이터의 타입을 변경하려면 astype

z = y.astype(np.float32) ; z

array([0., 1., 2., 3., 4.], dtype=float32)

In [38]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [40]:
arr + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [42]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [46]:
print(arr)
arr[:2,:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
# 0~ 11 값을 얻고 이를 4 X 3 배열로 재구성

data = np.arange(12).reshape(4, 3)
print(data)

arr = data.reshape(3, 4)
arr

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
data > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [61]:
# 5보다 큰 값만 교체하기

data[data > 5] = 100
data

array([[  0,   1,   2],
       [  3,   4,   5],
       [100, 100, 100],
       [100, 100, 100]])

In [67]:
# axis = 0 은 열별로 axis = 1은 행별로

data.mean(axis=1)

array([  1.,   4., 100., 100.])

In [75]:
#행 인덱스 순서로 위치 바꾸기 가능

print(data[[3, 2, 1, 0]])

# data 값은 변동 없다.

data


[[100 100 100]
 [100 100 100]
 [  3   4   5]
 [  0   1   2]]


array([[  0,   1,   2],
       [  3,   4,   5],
       [100, 100, 100],
       [100, 100, 100]])

In [77]:
data[data>5] =[6, 7, 8, 9, 10 ,11] 

In [84]:
# 행과 열을 모두 바꾸려면

data[[3,2,1,0]][:,[2, 1, 0]]

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [86]:
# 트랜스포즈는 행과 열의 위치 변경

data.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [88]:
# 배열의 곱셈은 np.dot()를 사용

np.dot(data,data.T)

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [93]:
#특정 수 보다 큰 원소의 갯수를 반환

print(data)
(data>4).sum()

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


7

In [96]:
data>4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [98]:
z = np.random.randint(0, 100, 10)
z

array([27, 56,  2, 42, 42, 20, 50, 30, 40, 89])

In [100]:
z.sort()
z

array([ 2, 20, 27, 30, 40, 42, 42, 50, 56, 89])

In [102]:
t = np.random.randint(0, 100, 12).reshape(3, 4)
t

array([[91, 57, 97, 97],
       [93, 17, 90, 17],
       [58,  6, 16, 60]])

In [104]:
# 열을 기준으로 정렬

t.sort(0)
t

array([[58,  6, 16, 17],
       [91, 17, 90, 60],
       [93, 57, 97, 97]])

In [106]:
# 행을 기준으로 정렬

t.sort(1)
t

array([[ 6, 16, 17, 58],
       [17, 60, 90, 91],
       [57, 93, 97, 97]])

In [107]:
# 순서를 임의로 바꾸기

np.random.permutation(t)

array([[57, 93, 97, 97],
       [ 6, 16, 17, 58],
       [17, 60, 90, 91]])